### ISSUE TITLE
Stuck on : Please connect your phone to the printer

### ISSUE THREAD

**Issue by Goribesh** [gaifeng8864/klipper-on-android#2]
Hello i followed all the procedure in the guide but the script cannot find my printer, i had to use oco4a in the previous installation cause my printer is based on ch341, any workaround?

**Comment by gaifeng8864** [comment]
Because the CH341 driver is not integrated in most Android systems, there is currently no good way to directly connect to the motherboard.
There are currently two options:
First, recompile the kernel with the ch341 driver.
The second one, use the "tcpuart" apk for transfer. Start "tcpuart", set the baud rate and port, then run this command in debian:
  socat -d -d pty,link=/tmp/tcpserial,raw,echo=0,waitslave tcp:localhost:8080
The mcu address in print.cfg is /tmp/tcpserial
But this method needs to set tcpuart.apk to start automatically, and the command "socat -d -d pty,link=/tmp/tcpserial,raw,echo=0,waitslave tcp:localhost:8080" also needs to be added to the debian boot sequence.

**Comment by Goribesh** [comment]
Thank ive been able to make it works with the second option !

**Comment by gaifeng8864** [comment]
> Thank you, ive been able to make it works with the second option!

Great work. Can you share how to set tcpuart autostart and socat -d -d pty,link=/tmp/tcpserial,raw,echo=0,waitslave tcp:localhost:8080 autostart?

**Comment by Goribesh** [comment]
I sadly wasnt able to autostart it, ive tried to create a init.d script but it seems to not be working... Im sadly not that expert with linux so im not sure what else i can try...

**Comment by gaifeng8864** [comment]
Thank you for your work. I'll look into it when I have time.

**Comment by Goribesh** [comment]
Ive changed every voice about serial in the file with the /tmp/tcpserial one

**Comment by kahupihu** [comment]
ok

**Comment by kahupihu** [comment]
I do not speak chinese 
But I'm dumb and followed every step including setting chinese locale and installing chinese fonts.
Is there any way to switch the whole thing to english?

**Comment by kahupihu** [comment]
Also, fluidd says that it cannot connect to moonraker... :'(

**Comment by kahupihu** [comment]
yeah

**Comment by Goribesh** [comment]
what do u mean? u should write /tmp/tcpserial in printer.cfg

**Comment by kahupihu** [comment]
oh 
my 
god

Im gonna give up...

![image](https://user-images.githubusercontent.com/66558551/207109306-3f3b2b42-1ca1-4cc3-a4a6-31b03bd124d0.png)

**Comment by kahupihu** [comment]
just an experiment

**Comment by Goribesh** [comment]
> just an experiment

u need to write /tmp/tcpserial in printer.cfg

**Comment by Goribesh** [comment]
and the app says its connected?

**Comment by kahupihu** [comment]
thats not my config
i have an ender 3 
i try to copy the config from an rpi i use for fluidd and it says bad request when I try to save....

**Comment by kahupihu** [comment]
the tcpuart is supposed to be server right?

**Comment by Goribesh** [comment]
yes

**Comment by kahupihu** [comment]
> oh my god
> 
> Im gonna give up...
> 
> ![image](https://user-images.githubusercontent.com/66558551/207109306-3f3b2b42-1ca1-4cc3-a4a6-31b03bd124d0.png)

**Comment by kahupihu** [comment]
Im gonna sleep after one more try...

**Comment by Goribesh** [comment]
and u need to connect with the 250000 baudrate

**Comment by kahupihu** [comment]
bruh

**Comment by kahupihu** [comment]
im gonna try that

**Comment by kahupihu** [comment]
oh my god! TYSM!

**Comment by kahupihu** [comment]
I hope you have a wonderful day!

**Comment by kahupihu** [comment]
Btw is a Lenovo k3 note k50a40 powerful enought to use timelapse?

**Comment by Goribesh** [comment]
I think the only way to know is try...

**Comment by kahupihu** [comment]
and can i even make timelapses on a phone?

**Comment by kahupihu** [comment]
like fluidd style timlapses

**Comment by kahupihu** [comment]
something like this:- **https://www.youtube.com/watch?time_continue=2&v=Z2ut7lGHWuQ&feature=emb_logo**

**Comment by kahupihu** [comment]
**test**

**Comment by Goribesh** [comment]
Ive never tried a timelapse so i dont know, but i know that u can use it as a webcam in theory

**Comment by kahupihu** [comment]
I just had an idea
Use an IP webcam application and copy the IP generated into klipper

**Comment by Goribesh** [comment]
yeah it should work

**Comment by kahupihu** [comment]
today, this keeps happening
2022/12/13 13:25:58 socat[22280] N read(5, 0x55ab22e000, 8192): Input/output error (probably PTY closed)
2022/12/13 13:25:58 socat[22280] N socket 1 (fd 5) is at EOF
2022/12/13 13:25:59 socat[22280] N exiting with status 0

**Comment by kahupihu** [comment]
nvm
![image](https://user-images.githubusercontent.com/66558551/207263817-e221caec-a0a5-4e32-bcd6-c776371c01b8.png)

**Comment by gaifeng8864** [comment]
> nvm ![image](https://user-images.githubusercontent.com/66558551/207263817-e221caec-a0a5-4e32-bcd6-c776371c01b8.png)

My god, how did you manage to use the camera?

**Comment by kahupihu** [comment]
The app is literally "IP camera" on play store

**Comment by kahupihu** [comment]
The url should be http://ip:port/video and type is mjepg adaptive

**Comment by kahupihu** [comment]
I used the port 8083

**Comment by Saurabh251-cmd** [comment]
> nvm ![image](https://user-images.githubusercontent.com/66558551/207263817-e221caec-a0a5-4e32-bcd6-c776371c01b8.png)

is your printer from Ender 3 wol3d?
