### ISSUE TITLE
Linux Deploy not installing Debian architecture 

### ISSUE THREAD

**Issue by sssawant17** [gaifeng8864/klipper-on-android#5]
After following your tutorial (here on Github as well as your video), I am running into following issue:
After hitting "Install", the screen immediately displays ">>> deploy" & "<<< deploy" in a matter of seconds.
upon checking the status,  I get the following response in the screenshot:

![Screenshot_20230214-112435_Linux_Deploy 1](https://user-images.githubusercontent.com/87416534/218723738-76a2c270-5aeb-41ee-8a3b-21aabbdb68c3.jpg)

Donor phone: Samsung Galaxy S8 (64 bit processor hence using "Arm64 architecture" option.

**Comment by gaifeng8864** [comment]
> After following your tutorial (here on Github as well as your video), I am running into following issue: After hitting "Install", the screen immediately displays ">>> deploy" & "<<< deploy" in a matter of seconds. upon checking the status, I get the following response in the screenshot:
> 
> ![Screenshot_20230214-112435_Linux_Deploy 1](https://user-images.githubusercontent.com/87416534/218723738-76a2c270-5aeb-41ee-8a3b-21aabbdb68c3.jpg)
> 
> Donor phone: Samsung Galaxy S8 (64 bit processor hence using "Arm64 architecture" option.

Can you provide the model of your mobile phone and the version of Android system you are using? And, what method does the Android system use to obtain root privileges?
The reason for this phenomenon is likely to be the incompatibility between the kernel of the Android system and the Debian system or the container virtualized by linuxdeploy. If this is the case, you can only try to change the Android system version.

**Comment by sssawant17** [comment]
The issue is resolved by re rooting teh phone with LineageOS

**Comment by gaifeng8864** [comment]
> The issue is resolved by re rooting teh phone with LineageOS

That's great, congratulations.
